apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
      - name: myapp-container
        image: nginx
replicas: 3


# kubectl create -f rc-definition.yml
    # replicationcontroller/myapp-rc created

# kubectl get replicationcontroller
    # NAME       DESIRED   CURRENT   READY   AGE
    # myapp-rc   3         3         3       3m

# kubectl get pods
    # NAME             READY   STATUS    RESTARTS   AGE
    # myapp-rc-2b5q2   1/1     Running   0          3m
    # myapp-rc-7b4q2   1/1     Running   0          3m
    # myapp-rc-8b4q2   1/1     Running   0          3m