apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 6
  selector:
    matchLabels:
      type: frontend



# kubectl create -f replicaset-definition.k8s.yaml
    # replicaset.apps/myapp-replicaset created

# kubectl get replicaset
    # NAME               DESIRED   CURRENT   READY   AGE
    # myapp-replicaset   3         3         3       3m

# kubectl get pods
    # NAME                     READY   STATUS    RESTARTS   AGE
    # myapp-replicaset-2b5q2   1/1     Running   0          3m
    # myapp-replicaset-7b4q2   1/1     Running   0          3m
    # myapp-replicaset-8b4q2   1/1     Running   0          3m




# kubectl replace -f replicaset-definition.k8s.yaml
    # replicaset.apps/myapp-replicaset replaced

# kubectl scale --replicas=6 -f replicaset-definition.k8s.yaml
    # replicaset.apps/myapp-replicaset scaled